### PR TITLE
Add support clickhouse

### PR DESCRIPTION
**Pull request by dmamontov**

### CODE REVIEW

**Comment by josefd8** [comment]
Hello @dmamontov 

Thank you very much for submitting a MR to GingerSpec! New collaborators are always welcome :)

Whenever a new commit is pushed to the project, the pipeline (Github workflow) automatically runs the tests to check that no functionality has been broken. In order to run the Feature files, several docker containers are initialized and the tests are executed against them. You can get an idea of how this works in the maven-build.yml.

A Postgres and a MySQL container are initialized to test the database-related functionality, and the feature is executed using this container. You will have to implement the steps to make sure that the functionality related to clickhouse is indeed working correctly

You will have to:

- Set up a new service for clickhouse in the maven-build.yml that will bootstrap the container during the building phase
- Implement the necessary steps in the [sqlDatabaseSteps.feature](https://github.com/veepee-oss/gingerspec/blob/master/src/test/resources/features/sqlDatabaseSteps.feature) to make sure all steps and functionality is working

Feature files are actually also used to auto-generate the documentation that you see [here](https://veepee-oss.github.io/gingerspec/). That's another reason why having the steps in place is very important: They create the documentation and make sure everything is working.

You can use the current implementation for Mysql and Postgres as a guideline. Let me know if you need any help to give you some guidance

Regards

**Comment by dmamontov** [comment]
Hello @josefd8 

I have added tests. At the same time, I found one flaw. Thank you for not accepting changes without testing)

**Review by josefd8 — COMMENTED** [review]
One question, isnt there an official image for clickhouse?

**Comment by dmamontov** [comment]
> One question, isnt there an official image for clickhouse?

It is, but not fully configured (not suitable for ci). Here is my image:

**Review by josefd8 — APPROVED** [review]

**Comment by dmamontov** [comment]
@josefd8 I think it's worth updating https://github.com/veepee-oss/gingerspec/blob/master/.github/workflows/maven-build.yml#L64. Because apparently and by action that fall (almost all fell because of this).

**Comment by josefd8** [comment]
@dmamontov I just updated the github-pages-deploy-action to 4.4.1. Lets see if that fixes the issue

**Comment by dmamontov** [comment]
@josefd8 There's a 403 error (https://github.com/veepee-oss/gingerspec/actions/runs/3610003103/jobs/6084079880#step:7:73).

**Comment by josefd8** [comment]
Yes, not sure why github-actions does not have permissions to the repository. I'll check

**Comment by dmamontov** [comment]
There is such a setting: https://github.com/veepee-oss/gingerspec/settings/actions

image

**Comment by josefd8** [comment]
Yes that's how it looks right now. And I've never touched this setting before

Captura de Pantalla 2022-12-03 a las 23 06 39

**Comment by dmamontov** [comment]
I'm just trying to compare with my repository) everything works fine in it.

**Comment by josefd8** [comment]
Im not sure if maybe the problem could be because it is coming from a fork that is in a repo outside the organization and the

**Comment by dmamontov** [comment]
https://github.com/JamesIves/github-pages-deploy-action/issues/1229

Here is an issue about the bug. But no solution

**Comment by josefd8** [comment]
The 128 code is more the status code of the executed command, but the real reason is the 403, which is a forbidden

**Comment by dmamontov** [comment]
Sorry) My eyes are already blurry) I worked all day)

**Comment by josefd8** [comment]
we can continue this tomorrow :) no worries. If it is indeed a problem with the actions plugin, I could Merge the pull request and then push myself the pages to gh-pages branch

**Comment by dmamontov** [comment]
I'm not worried) I just want to help) There are other ideas that would be useful to add) And here is a message from the plugin [documentation](https://github.com/marketplace/actions/deploy-to-github-pages#getting-started-airplane):

image

**Comment by josefd8** [comment]
Tried adding  `permissions: contents: write` to workflow but nothing. I find this error very strange

**Comment by josefd8** [comment]
And I see in your repo the gh-pages branch was created successfully, so I don't think is a problem with the actions plugin

**Comment by dmamontov** [comment]
Yes.  I think it's magic) It's time for me to rest, tomorrow I can help to look for the reason further) if you don't find it before me)

P.S. Pipes started to give an error since September 4th.

**Comment by josefd8** [comment]
Hi @dmamontov good day.

I proceed and merge the PR and now it magically works :). I guess that t was because the MR was coming from an external repo as I mentioned. 

Why did you create the MR from a fork and not directly by creating a branch in the gingerspec repo?

**Comment by dmamontov** [comment]
@josefd8 I'm just experimenting in my fork) I'll do it right next time)

**Comment by josefd8** [comment]
Great :) thank you.

If you need it, I could generate a new release (2.2.14) with your clickhouse changes, so you can use it right away in your projects. Although it usually takes like around 1 day to be available in Maven central repository

**Comment by dmamontov** [comment]
It would be cool. Thank you)

**Pull request merged**
