### PR TITLE
Add support graphql

### PR DESCRIPTION
**Pull request by dmamontov**
@josefd8 Unfortunately, I can’t launch directly in your repository, so the PR) Again, the generation of documents will probably fall)

And so I added support for GraphQL)

### CODE REVIEW

**Comment by josefd8** [comment]
Hey @dmamontov ,

Thanks for the PR :) I'll give it a look tomorrow or later today since I'm going to be busy all afternoon.

One thing I was thinking though: Idk if it would be a good idea to put the steps and all functions related to graphql in a separate Feature file, that way it will have its own documentation.

Although it also makes sense for it to be in restAssured.feature, but my concern is that that feature already has so many steps that it could look a bit cramped

**Comment by dmamontov** [comment]
@josefd8 The problem is that graphql is in principle only a format, if it is taken out separately there will be many duplicates. I think you can restructure the file with the test, as in the future I will still need to add support for the swagger, async api and protobuf schemas (in fact, these are only schemas).

**Comment by dmamontov** [comment]
@josefd8 Slightly changed the structure for the documentation and in the near future I want to add support for swagger + automatic generation based on it

**Comment by josefd8** [comment]
hey @dmamontov

I was quickly checking the changes, looks good to me. I was just wondering if there's any other change you would like to make before I merge?

I see you created a new Rule inside the feature to organize the steps for Grapql, that's a good approach :)

**Comment by dmamontov** [comment]
Hey @josefd8.

Until I add something new. Now I want to add swagger support. But this takes more time.

**Review by josefd8 — APPROVED** [review]

**Comment by dmamontov** [comment]
Hi @josefd8

And you can ask to roll out a new version. I really need the edits I made.

**Comment by josefd8** [comment]
Hey @dmamontov 

Sure, I will generate 2.2.15. Although it wont be available inmediatly

**Comment by dmamontov** [comment]
@josefd8 Thanks

**Pull request merged**
